name: 'Build sphinx docs'
description: 'Builds IDS Sphinx documentation'
inputs:
  docs_path: # id of input
    description: 'The path to the documentation folder from the repo root'
    required: false
    default: 'docs'
  conda_build_env_filepath:
    description: 'Yaml Conda build environment definition file'
    required: false
    default: 'action_default'
  base_env_prefix:  # id of input
    description: 'The prefix of the base Conda environment for self-hosted runs.'
    required: false
    default: '/usr/share/miniconda'
  artifact_name:
    description: 'Display name of the documentation artifact'
    required: false
    default: 'documentation'
  package_folder_path:
    description: 'Path to the folder containing the project''s package(s) to be installed'
    required: false
    default: 'conda_package'
  package_name:
    description: 'Name of the project''s Conda package'
    required: false
    default: ${{ github.event.repository.name }}
  package_conda_channels:
    description: 'conda channels needed to install package. Spearate each channel with -c.'
    required: False
    default: conda-forge
  build_subdir_name:
    description: 'docs will be built inside docs_path in build/{build_subdir_name}.'
    required: False
    default: 'html'
outputs:
  filepath:
    description: 'The file path of the generated HTML documentation'
    value: ${{ steps.main.outputs.filepath }}
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - id: main
      run: |
        echo "::set-output name=filepath::$(echo "None")"
        echo "CHECKS"
        echo "------"
        if [ -d ${{ inputs.docs_path }} ]; then
          echo "  Found the docs folder at ${{ inputs.docs_path }}"
        else
          echo "  ERROR: Unable to locate the docs path, ${{ inputs.docs_path }}. Skipping the build of the docs."
          exit 0
        fi
        echo ""
        echo "Selecting Build Env yml File"

        if [ ${{ inputs.conda_build_env_filepath }} = 'action_default' ]; then
          echo "Using the default conda configuration"
          CONDA_BUILD_ENV_FILE="${{ github.action_path }}/envs/build-docs.yml"
        elif [ -f ${{ inputs.conda_build_env_filepath }} ]; then
          CONDA_BUILD_ENV_FILE=${{ inputs.conda_build_env_filepath }}
        else
          echo "Using the default conda configuration"
          CONDA_BUILD_ENV_FILE="${{ github.action_path }}/envs/build-docs.yml"
        fi
        echo "CONDA_BUILD_ENV_FILE: ${CONDA_BUILD_ENV_FILE=}"
        cat "${CONDA_BUILD_ENV_FILE}"

        echo "Checking that Conda is initialized"
        if ! command -v conda &> /dev/null; then
          echo "Conda is not setup.  Attempting to set it up."
          echo 'source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh'
          source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh
          if ! command -v conda &> /dev/null; then
            echo "ERROR: Failed to setup setup Conda"
            exit 1
          fi
        fi
        echo "  Conda is initialized"

        echo ""
        echo "SETUP BUILD ENV"
        echo "Set source"
        source ${{ inputs.base_env_prefix }}/etc/profile.d/conda.sh
        echo "-----------------"
        
        echo "Setting up ${{ github.event.repository.name }}-build environment"
        conda config --set channel_priority true
        conda create -n ${{ github.event.repository.name }}-build python=3.7 -c conda-forge

        conda activate ${{ github.event.repository.name }}-build
        conda install conda-build -c conda-forge
        ls -al ${{ inputs.package_folder_path }}
        echo "----------------"
        if [ -a ${{ inputs.package_folder_path }}/${{ inputs.package_name }}-*.bz2 ]; then
          echo "Installing project package"
          CHANNEL_PATH="${{runner.temp}}/channel/linux-64"
          mkdir -p "${CHANNEL_PATH}"
          cp ${{ inputs.package_folder_path }}/${{ inputs.package_name }}-*.bz2 ${CHANNEL_PATH}
          ls -al ${CHANNEL_PATH}
          conda index "${CHANNEL_PATH}"
          echo "SHOW CHANNELS"
          conda config --show channels
          echo "SEARCHING CHANNEL"
          conda search -c ${CHANNEL_PATH} ${{ inputs.package_name }} | grep channel
          conda search -c ${CHANNEL_PATH} ${{ inputs.package_name }}
          PACKAGE_FILE=$(ls ${CHANNEL_PATH})
          VERSION_STRING=$(basename ${PACKAGE_FILE} .tar.bz2 | tr '-' '=')
          conda install $VERSION_STRING -c "${CHANNEL_PATH}" -c ${{inputs.package_conda_channels}}
        else
          echo "Did not install project package"
        fi
        
        conda env update --name ${{ github.event.repository.name }}-build \
          --file "${CONDA_BUILD_ENV_FILE}"


        
        echo ""
        echo "conda info"
        conda info
        echo ""
        echo "conda list"
        conda list

        echo ""
        echo "BUILD DOCS"
        echo "----------"
        cd ${{ inputs.docs_path }}
        if [ -e "./setup_source.sh" ]; then
          ./setup_source.sh
        fi
        sphinx-build source build/${{ inputs.build_subdir_name }}
        echo "::set-output name=filepath::$(echo '${{ inputs.docs_path }}/build')"
      shell: bash -l {0}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.docs_path }}/build
branding:
  icon: 'book-open'
  color: 'blue'
